---
engines:
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  scsslint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.scss"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
- Capfile
- Gemfile*
- public/**/*
- bin/**/*
- config.ru
