image:
  name: ruby:2.5.5

variables:
  DISPLAY_SOCIAL_MOBILITY_AWARD: "true"
  POSTGRES_DB: qae_test
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"
  PHANTOM_JS: phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64
  BUNDLER_VERSION: 2.0.1

services:
  - name: redis:3.2.7
  - name: postgres:9.6-alpine
    alias: postgres

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y postgresql postgresql-client
    - apt-get install -y nodejs
    - wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.gz
    - tar xzvf $PHANTOM_JS.tar.gz
    - mv phantomjs-2.5.0-beta-ubuntu-xenial /usr/local/share
    - ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
    - phantomjs --version
    - gem install bundler
    - bundle install --path vendor/bundler --jobs=4 --retry=3
    - RAILS_ENV=test bundle exec rake db:create db:migrate
  script:
    - RAILS_ENV=test RAILS_DISABLE_TEST_LOG=true bundle exec rspec --tag '~skip_ci' --format RspecJunitFormatter --out rspec.xml --format progress
  artifacts:
    reports:
      junit: rspec.xml
  cache:
    key: gems-cache
    paths:
      - vendor/bundler

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export DOCKER_HOST=tcp://localhost:2375
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]

deploy_dev:
  stage: deploy
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - dpkg -i cf-cli_amd64.deb
    - cf -v
    - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
    - cf install-plugin blue-green-deploy -r CF-Community -f
    - CF_ENDPOINT=api.london.cloud.service.gov.uk CF_SPACE=dev CF_APP=qae-dev ./bin/deploy
  environment:
    name: dev
    url: https://dev.queens-awards-enterprise.service.gov.uk/
  only:
    - master

deploy_staging:
  stage: deploy
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - dpkg -i cf-cli_amd64.deb
    - cf -v
    - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
    - cf install-plugin blue-green-deploy -r CF-Community -f
    - CF_ENDPOINT=api.london.cloud.service.gov.uk CF_SPACE=staging CF_APP=qae-staging ./bin/deploy
  environment:
    name: staging
    url: https://staging.queens-awards-enterprise.service.gov.uk/
  only:
    - staging

deploy_production:
  stage: deploy
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - dpkg -i cf-cli_amd64.deb
    - cf -v
    - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
    - cf install-plugin blue-green-deploy -r CF-Community -f
    - CF_ENDPOINT=api.london.cloud.service.gov.uk CF_SPACE=production CF_APP=qae-production ./bin/deploy
  environment:
    name: production
    url: https://www.queens-awards-enterprise.service.gov.uk/
  when: manual
  only:
  - production
