image:
  name: ruby:2.5.0

variables:
  POSTGRES_DB: qae_test
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  PHANTOM_JS: phantomjs-2.1.1-linux-x86_64

services:
  - name: redis:3.2.7
  - name: postgres:9.6-alpine
    alias: postgres

stages:
  - test
  - deploy

test:
  stage: test


code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]


deploy_staging:
  stage: deploy
  script:
    - curl -L https://convox.com/cli/linux/convox -o /tmp/convox
    - mv /tmp/convox /usr/local/bin/convox
    - chmod 755 /usr/local/bin/convox
    - convox deploy --app qae-staging --rack bitzesty/qae
    - convox run web rake db:migrate --app qae-staging --rack bitzesty/qae
  environment:
    name: dev
    url: https://staging.queens-awards-enterprise.service.gov.uk/
  only:
    - staging

deploy_production:
  stage: deploy
  script:
    - curl -L https://convox.com/cli/linux/convox -o /tmp/convox
    - mv /tmp/convox /usr/local/bin/convox
    - chmod 755 /usr/local/bin/convox
    - convox deploy --app qae-production --rack bitzesty/qae
    - convox run web rake db:migrate --app qae-production --rack bitzesty/qae
  environment:
    name: production
    url: https://www.queens-awards-enterprise.service.gov.uk/
  when: manual
  only:
  - production
