image:
  name: ruby:2.5.0

variables:
  POSTGRES_DB: qae_test
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  PHANTOM_JS: phantomjs-2.1.1-linux-x86_64

services:
  - name: redis:3.2.7
  - name: postgres:9.6-alpine
    alias: postgres

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y postgresql-client
    - apt-get install -y nodejs
    - wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
    - tar xvjf $PHANTOM_JS.tar.bz2
    - mv $PHANTOM_JS /usr/local/share
    - ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
    - phantomjs --version
    - bundle install --jobs 4 --retry 3 --path vendor
    - RAILS_ENV=test bundle exec rake db:create db:migrate
  script:
    - RAILS_ENV=test RAILS_DISABLE_TEST_LOG=true bundle exec rspec spec/ --tag '~skip_ci' --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
  cache:
    key: gems-cache
    paths:
      - vendor/ruby

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]

deploy_dev:
  stage: deploy
  script:
    - curl -L https://convox.com/cli/linux/convox -o /tmp/convox
    - mv /tmp/convox /usr/local/bin/convox
    - chmod 755 /usr/local/bin/convox
    - convox deploy --app qae-dev --rack bitzesty/qae
    - convox run web rake db:migrate --app qae-dev --rack bitzesty/qae
  environment:
    name: dev
    url: https://dev.queens-awards-enterprise.service.gov.uk/
  only:
    - master

deploy_staging:
  stage: deploy
  script:
    - curl -L https://convox.com/cli/linux/convox -o /tmp/convox
    - mv /tmp/convox /usr/local/bin/convox
    - chmod 755 /usr/local/bin/convox
    - convox deploy --app qae-staging --rack bitzesty/qae
    - convox run web rake db:migrate --app qae-staging --rack bitzesty/qae
  environment:
    name: dev
    url: https://staging.queens-awards-enterprise.service.gov.uk/
  only:
    - staging

deploy_production:
  stage: deploy
  script:
    - curl -L https://convox.com/cli/linux/convox -o /tmp/convox
    - mv /tmp/convox /usr/local/bin/convox
    - chmod 755 /usr/local/bin/convox
    - convox deploy --app qae-production --rack bitzesty/qae
    - convox run web rake db:migrate --app qae-production --rack bitzesty/qae
  environment:
    name: production
    url: https://www.queens-awards-enterprise.service.gov.uk/
  when: manual
  only:
  - production
