language: ruby
rvm:
  - 2.1.5
addons:
  postgresql: 9.3
before_script:
  - /bin/cp $TRAVIS_BUILD_DIR/config/database.yml.example $TRAVIS_BUILD_DIR/config/database.yml
  - /bin/cp $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env
  - psql -c 'create database qae_test;' -U postgres
