version: "2"
services:
  web:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    environment:
      - PORT=3000
      - SECRET_KEY_BASE=PLACEHOLDERSECRETBASEKEY
      - RAILS_SERVE_STATIC_FILES=enabled
      - LANG=en_US.UTF-8
      - RAILS_ENV=production
      - RACK_ENV=production
    labels:
      - convox.port.443.protocol=https
      - convox.deployment.minimum=50
    ports:
      - 80:3000/tcp
      - 443:3000/tcp
  worker:
    build:
      context: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - SECRET_KEY_BASE=PLACEHOLDERSECRETBASEKEY
      - LANG=en_US.UTF-8
      - RAILS_ENV=production
      - RACK_ENV=production
