web: &web
  build: .
  command: bundle exec puma -C config/puma.rb
    environment:
    - RACK_ENV=development
    - RAILS_ENV=development
  ports:
    - '80:3000'
    - '443:3000'
  volumes:
    - .:/app
worker:
  <<: *web
  ports: []
  command: bundle exec sidekiq
