# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f83c05133b23891a1a7022a06f583676616937990fa8fd26ee760791f8e9b596f8fed36b39b9536e54a84120274f72038a50fd49e58b7359ef990cbdccfff11d

test:
  secret_key_base: 8423684d23b2ffb525f01e484ec93d3e27802f469bab7b7b17d4c74b7832e294f7c86cf114ae08e30635e9dcc56186c311507c8d193d37a68343ee0f1d0c1596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
