aws:
  access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             <%= ENV['AWS_REGION'] %>
  receive_message:              # See http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/SQS/Queue.html#receive_message-instance_method
    # wait_time_seconds: 1        # The number of seconds to wait for new messages when polling. Defaults to the #wait_time_seconds defined on the queue
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
concurrency: 4,  # The number of allocated threads to process messages. Default 25
delay: 5,        # The delay in seconds to pause a queue when it's empty. Default 0
queues:
  - ["<%= ENV['AWS_SQS_QUEUE_ADVANCED_PREFIX'].to_s %><%= Rails.env %>_mailers", 1]
  - ["<%= ENV['AWS_SQS_QUEUE_ADVANCED_PREFIX'].to_s %><%= Rails.env %>_default", 2]
