- id: "financial_year_changed_dates"
  label: "Financial year dates"
- id: "employees"
  label: "Number of people employed"
- id: "total_turnover"
  label: "Total turnover"
- id: "exports"
  label: "Exports"
- id: "net_profit"
  label: "Net profit after tax but before dividends"
- id: "total_net_assets"
  label: "Total net assets"
- id: "units_sold"
  label: "Number of innovative units/contracts sold"
- id: "sales"
  label: "Sales of innovative product/service"
- id: "sales_exports"
  label: "Sales exports"
- id: "sales_royalties"
  label: "Sales royalties or licenses"
- id: "avg_unit_price"
  label: "Average unit selling price/contract value"
- id: "avg_unit_cost_self"
  label: "Direct cost of a single unit/contract"
