- id: "innovation"
  name: "Innovation Award"
  labels:
    - id: "employees"
      label: "State the number of full-time employees (or part-time equivalent) employed in the UK by the entrant at the end of each 12 month period or as an average for each year"
    - id: "total_turnover"
      label: "Total Turnover"
    - id: "net_profit"
      label: "Net Profit (i.e. after tax, before dividends)"
    - id: "uk_sales"
      label: "UK sales"
    - id: "exports"
      label: "Export sales"
    - id: "units_sold"
      label: "Number of units/contracts/quantity sold"
    - id: "sales"
      label: "Actual sales"
    - id: "sales_exports"
      label: "of which exports"
    - id: "sales_royalties"
      label: "of which royalties or licences"
    - id: "avg_unit_cost_self"
      label: "(if applicable) Unit costs"
    - id: ""
      label: "Provide the cost savings if known, to your business or your customers' business after introduction of the innovation"
- id: "trade"
  name: "International Trade Award"
  labels:
    - id: "employees"
      label: "State the number of full-time employees (or part-time equivalent) employed in the UK by the entrant at the end of each 12 month period or as an average for each year"
    - id: "total_turnover"
      label: "Total Turnover (home plus overseas)"
    - id: "net_profit"
      label: "Net Profit (i.e. after tax, before dividends)"
- id: "development"
  name: "Sustainable Development Award"
  labels:
    - id: "employees"
      label: "State the number of full-time employees (or part-time equivalent) employed in the UK by the entrant at the end of each 12 month period or as an average for each year"
    - id: "total_turnover"
      label: "Total Turnover"
    - id: "net_profit"
      label: "Net Profit (i.e. after tax, before dividends)"
    - id: ""
      label: "Annual balance sheet total"
    - id: "uk_sales"
      label: "UK sales"
    - id: "exports"
      label: "Export sales"
    - id: "units_sold"
      label: "Number of units/contracts/quantity sold"
    - id: "sales"
      label: "Actual sales"
    - id: "sales_exports"
      label: "of which exports"
    - id: "sales_royalties"
      label: "of which royalties or licences"
    - id: "avg_unit_cost_self"
      label: "(if applicable) Unit costs"
    - id: ""
      label: "Provide the cost savings, if known, to your business or your customers' business after introduction of the new product or service"




